build: off

clone_folder: c:\gopath\src\github.com\go-echarts\go-echarts

environment:
  GOPATH: c:\gopath

stack:
  - go 1.11
  - go 1.12
  - go 1.13

before_test:
  - go get -t -v ./...
  - go vet ./...

test_script:
  - go test -v ./...
